services:
  db:
    image: postgres:latest
    networks:
      - nginxproxymanager_default
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: marketplace_db
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  redis:
    image: redis:7.2-alpine
    container_name: redis_marketplace
    networks:
      - nginxproxymanager_default
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    networks:
      - nginxproxymanager_default
    depends_on:
      - db
      - redis
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:root@db:5432/marketplace_db
      REDIS_PUBLIC_URL: redis://redis:6379

  frontend:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    networks:
      - nginxproxymanager_default
    depends_on:
      - api
    expose:
      - "3001"
    ports:
      - "3001:3001"
    environment:
      NEXT_PUBLIC_API_URL: "http://89.117.33.60:8080/api"
      NEXT_PUBLIC_FRONT_END_URL: "http://89.117.33.60:3001"

networks:
  nginxproxymanager_default:
    name: nginxproxymanager_default
    external: true

volumes:
  redis-data: