services:
  db:
    image: postgres:latest
    networks:
      - nginxproxymanager_default
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: marketplace_db
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  node:
    image: "node:22"
    user: "root"
    working_dir: /home/node/app
    volumes:
      - ./apps/api:/home/node/app
    networks:
      - nginxproxymanager_default
    depends_on:
      - db
    expose:
      - "8080"
    ports:
      - "8080:8080"
    entrypoint: sh -c 'set -e && npm install --legacy-peer-deps && npx prisma db push && npx prisma generate && npm run seed-db && npx tsc -p tsconfig.build.json && npm run start:prod'

  frontend:
    image: "node:22-alpine"
    user: "root"
    working_dir: /home/node/web
    environment:
      NEXT_PUBLIC_API_URL: "http://89.117.33.60:8080"
      NEXT_PUBLIC_FRONT_END_URL: "http://89.117.33.60:3001"
    volumes:
      - ./apps/web:/home/node/web
    networks:
      - nginxproxymanager_default
    depends_on:
      - node
    expose:
      - "3001"
    ports:
      - "3001:3001"
    entrypoint: sh -c 'npm install && npm run build && npm run start'

networks:
  nginxproxymanager_default:
    name: nginxproxymanager_default
    external: true